ignite-2190
nizhikov/ignite pull request #3
Opened 2017-05-28 14:49 UTC by nizhikov

* fix issue
* Added GridCacheEmptyScanQueryTest to reproduce bug described in task
* Minor fixes in IgniteProcessProxy and GridAbstractTest for a possibility to modify separate jvm grid classpath
* Added ignite-2190-1.0.jar to binary dependencies(source can be obtained from https://github.com/nizhikov/ignite-2190-binary)

2017-05-29 09:53 UTC, daradurvs requested changes
Need to make code style according to https://cwiki.apache.org/confluence/display/IGNITE/Coding+Guidelines

2017-05-29 09:53 UTC, daradurvs commented on modules/core/src/main/java/org/apache/ignite/internal/binary/BinaryObjectImpl.java
> +        if (coCtx == null)
New line requered

2017-05-29 09:53 UTC, daradurvs commented on modules/core/src/main/java/org/apache/ignite/internal/binary/BinaryObjectImpl.java
> +        BinaryReaderExImpl reader = reader(null, clsLdr, true);
New line

2017-05-29 09:53 UTC, daradurvs commented on modules/core/src/test/binaries/repo/org/apache/ignite/binary/ignite-2190/1.0/ignite-2190-1.0.pom
> +<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
Apache license header requered

2017-05-29 09:53 UTC, daradurvs commented on modules/core/src/test/binaries/repo/org/apache/ignite/binary/ignite-2190/maven-metadata-local.xml
> +<metadata>
Apache license header requered

2017-05-29 09:53 UTC, daradurvs commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/query/GridCacheEmptyScanQueryTest.java
> +package org.apache.ignite.internal.processors.cache.query;
Apache license header requered

2017-05-29 09:53 UTC, daradurvs commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/query/GridCacheEmptyScanQueryTest.java
> + * @author NIzhikov
@author isn't allowed, just the class description is needed

2017-05-29 09:53 UTC, daradurvs commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/query/GridCacheEmptyScanQueryTest.java
> +     */
Oneline javadoc style requered and 'dot' in the end

2017-05-29 09:53 UTC, daradurvs commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/query/GridCacheEmptyScanQueryTest.java
> +    @Override protected boolean isMultiJvm() {
/** {@inheritDoc} */

2017-05-29 09:53 UTC, daradurvs commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/query/GridCacheEmptyScanQueryTest.java
> +    public void testEmptyScanQueryWithOptimizedMarshaller() throws Exception {
javadoc is necessary. For example:
/**
     * @throws Exception If failed.
     */

2017-05-29 09:53 UTC, daradurvs commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/query/GridCacheEmptyScanQueryTest.java
> +    public void testEmptyScanQueryWithBinaryMarshaller() throws Exception {
javadoc

2017-05-29 09:53 UTC, daradurvs commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/query/GridCacheEmptyScanQueryTest.java
> +    public void testEmptyScanQuery2WithOptimizedMarshaller() throws Exception {
javadoc

2017-05-29 09:53 UTC, daradurvs commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/query/GridCacheEmptyScanQueryTest.java
> +    public void testEmptyScanQuery2WithBinaryMarshaller() throws Exception {
javadoc

2017-05-29 09:53 UTC, daradurvs commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/query/GridCacheEmptyScanQueryTest.java
> +    public void testEmptyScanQuery3WithOptimizedMarshaller() throws Exception {
javadoc

2017-05-29 09:53 UTC, daradurvs commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/query/GridCacheEmptyScanQueryTest.java
> +    public void testEmptyScanQuery3WithBinaryMarshaller() throws Exception {
javadoc

2017-05-29 09:53 UTC, daradurvs commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/query/GridCacheEmptyScanQueryTest.java
> +    public void runEmptyScanQuery(ScanQuery<Integer, Employee> query, int expectedSize,
javadoc.
query -> qry
expectedSize -> expSz
https://cwiki.apache.org/confluence/display/IGNITE/Abbreviation+Rules

2017-05-29 09:53 UTC, daradurvs commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/query/GridCacheEmptyScanQueryTest.java
> +    private IgniteConfiguration getLocalConfiguration() throws Exception {
javadoc

2017-05-29 09:53 UTC, daradurvs commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/query/GridCacheEmptyScanQueryTest.java
> +    @Override protected IgniteProcessProxy igniteProcessProxy(IgniteConfiguration cfg, Ignite locNode,
javadoc

2017-05-29 09:53 UTC, daradurvs commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/query/GridCacheEmptyScanQueryTest.java
> +                    if ("-cp".equals(arg) || "-classpath".equals(arg)) {
new line

2017-06-01 15:43 UTC, BiryukovVA requested changes
Need to make code style according to https://cwiki.apache.org/confluence/display/IGNITE/Coding+Guidelines

2017-06-01 15:43 UTC, BiryukovVA commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/query/GridCacheEmptyScanQueryTest.java
> +        return cfg;
new line

2017-06-01 15:43 UTC, BiryukovVA commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/query/GridCacheEmptyScanQueryTest.java
> +        return cfg;
new line

2017-06-01 15:43 UTC, BiryukovVA commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/query/GridCacheEmptyScanQueryTest.java
> +                for (String aClasspathArr : classpathArr) {
new line

2017-06-01 15:43 UTC, BiryukovVA commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/query/GridCacheEmptyScanQueryTest.java
> +                        classpath += (classpath.length() > 0 ? pathSeparator : "") + aClasspathArr;
one line "if" without "{}"

2017-06-01 15:43 UTC, BiryukovVA commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/query/GridCacheEmptyScanQueryTest.java
> +                return classpath;
new line

2017-06-01 15:43 UTC, BiryukovVA commented on modules/core/src/test/java/org/apache/ignite/testframework/junits/multijvm/IgniteProcessProxy.java
> +        return filteredJvmArgs;
new line

2017-06-05 09:08 UTC, BiryukovVA requested changes

2017-06-05 09:08 UTC, BiryukovVA commented on modules/core/src/test/java/org/apache/ignite/testframework/junits/multijvm/IgniteProcessProxy.java
> +        return filteredJvmArgs;
rerurn need to start from a new line.

2017-06-05 20:00 UTC, closed without merging