IGNITE-5712: context switch for tx
nizhikov/ignite pull request #7
Opened 2017-07-20 09:54 UTC by nizhikov

implementation for tx suspend/resume operation. Resume and following commit can be executed in other thread.

2017-07-20 12:26 UTC, voipp commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxAdapter.java
> +
// No-op.

2017-07-20 12:26 UTC, voipp commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxLocalState.java
> +    public void unseal();
need sensible description

2017-07-20 12:26 UTC, voipp commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxManager.java
> +    public static final long UNDEFINED_THREAD_ID = -1L;
need sensible description

2017-07-20 12:26 UTC, voipp commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxImplicitSingleStateImpl.java
> +    @Override public void unseal() {
javadoc

2017-07-20 12:26 UTC, voipp commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearTxLocal.java
> +                cctx.tm().resumeTx(this);
we can eliminate resumeInProgress variable and put synchronized logic into resumeTx().

2017-07-20 12:26 UTC, voipp commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxManager.java
> +        assert !transactionMap(tx).containsValue(tx);
When we initiate transaction locally it becomes local and near, so change to idMap.containsValue(tx).
You can assert GridNearTxLocal is near and local

2017-07-20 12:26 UTC, voipp commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxManager.java
> +        clearThreadMap(tx);
can be changed just to threadMap.remove

2017-07-20 12:26 UTC, voipp commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxManager.java
> +        transactionMap(tx).remove(tx.xidVersion(), tx);
GridNearTxLocal is near and local, so change to idMap.containsValue(tx)

2017-07-20 12:26 UTC, voipp commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxManager.java
> +                if (sysThreadMap.containsKey(new TxThreadKey(threadId, cacheCtx.cacheId())))
why we cannot resume\suspend user tx when system tx is active on the current thread?

2017-07-20 12:26 UTC, voipp commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxManager.java
> +        ConcurrentMap<GridCacheVersion, IgniteInternalTx> txIdMap = transactionMap(tx);
idMap.containsValue(tx)

2017-07-20 12:26 UTC, voipp commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/AbstractTransactionsInMultipleThreadsTest.java
> +            assertTrue(txMgr.activeTransactions().isEmpty());
need to clean active transactions if any before throwning assertion

2017-07-20 12:26 UTC, voipp commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearTxLocal.java
> +    private ThreadLocal<Boolean> suspendInProgress = new ThreadLocal<Boolean>() {
nooooo

2017-07-20 12:26 UTC, voipp commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearTxLocal.java
> +        if (pessimistic() || system()) {
move checking to tm().suspendTx() so there is no asser\exception checking duplication, eliminate suspendInProgress

2017-07-20 12:26 UTC, voipp commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearTxLocal.java
> +        if (threadId() != Thread.currentThread().getId())
move checking to tm().suspendTx() to  eliminate suspendInProgress

2017-07-20 12:26 UTC, voipp commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/AbstractTransactionsInMultipleThreadsTest.java
> +                throw new RuntimeException(e);
IgniteException

2017-07-20 12:38 UTC, voipp commented on modules/core/src/test/java/org/apache/ignite/testsuites/IgniteCacheTestSuite6.java
> +        suite.addTestSuite(IgniteOptimisticTxSuspendResumeTest.class);
we dont need to decouple tests into new IgniteOptimisticTxSuspendResumeTest and create separate test suite.

2017-07-20 12:38 UTC, voipp commented on modules/jta/src/test/java/org/apache/ignite/internal/processors/cache/GridJtaTransactionManagerSelfTest.java
> +public class GridJtaTransactionManagerSelfTest extends GridCacheAbstractSelfTest {
we need to add tests for JTA or create separate ticket for it and do it in future. Tests scenarious must be the same(concurrency tests superflows)

2017-07-20 12:48 UTC, nizhikov commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxAdapter.java
> +
done

2017-07-20 12:50 UTC, nizhikov commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxManager.java
> +    public static final long UNDEFINED_THREAD_ID = -1L;
done

2017-07-20 12:52 UTC, nizhikov commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxManager.java
> +        clearThreadMap(tx);
As far as I can see other methods use clearThreadMap.
Moreover common method for clearing allows some additional checks and actions inside it.

2017-07-20 12:55 UTC, nizhikov commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxManager.java
> +        transactionMap(tx).remove(tx.xidVersion(), tx);
As far as I can see other method use transactionMap.
Moreover common method for obtaining map allows some additional checks and actions inside it.
Future logic can be extended so it better to use transactionMap method

2017-07-20 12:56 UTC, nizhikov commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxManager.java
> +        assert !transactionMap(tx).containsValue(tx);
As far as I can see other method use transactionMap.
Moreover common method for obtaining map allows some additional checks and actions inside it.
Future logic can be extended so it better to use transactionMap method.

2017-07-20 12:57 UTC, nizhikov commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxManager.java
> +                if (sysThreadMap.containsKey(new TxThreadKey(threadId, cacheCtx.cacheId())))
Can we?

2017-07-20 12:58 UTC, nizhikov commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxManager.java
> +        ConcurrentMap<GridCacheVersion, IgniteInternalTx> txIdMap = transactionMap(tx);
Can't understand this comment? Can you clarify what it means?

2017-07-20 12:59 UTC, nizhikov commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxImplicitSingleStateImpl.java
> +    @Override public void unseal() {
done

2017-07-20 13:01 UTC, nizhikov commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearTxLocal.java
> +        if (pessimistic() || system()) {
suspendInProgress unlocks change of threadId outside instance.
See threadId(long threadId) method.

2017-07-20 13:04 UTC, nizhikov commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearTxLocal.java
> +        if (pessimistic() || system()) {
done

2017-07-20 15:08 UTC, voipp commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxManager.java
> +        clearThreadMap(tx);
all checks must be above , btw

2017-07-20 15:15 UTC, voipp commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxManager.java
> +        assert !transactionMap(tx).containsValue(tx);
you need to add assert tx.near() && tx.local()

2017-07-20 15:52 UTC, nizhikov commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxImplicitSingleStateImpl.java
> +    @Override public void unseal() {
done

2017-07-21 12:41 UTC, daradurvs requested changes

2017-07-21 12:41 UTC, daradurvs commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearTxLocal.java
> +    /** Flag to indicate that current thread perform transaction suspension. */
Если это не нарушит логику, можно ввести поле txState
и private static enum состояний.
Либо расширить enum TransactionState дополнительными состояниями и логику проверки связаться с методом state() класса

2017-07-21 12:41 UTC, daradurvs commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearTxLocal.java
> +    private AffinityTopologyVersion txTopForSuspension;
Если это кэшируется для потока, то может сделать ThreadLocal?
А если кэшируется для нескольких потоков, не будет ли не согласованного состояние? volatile?

2017-07-21 12:41 UTC, daradurvs commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearTxLocal.java
> +
В методе resume(), подобны блок обернут в synchronized (this). Возможно здесь забыто?

2017-07-21 12:41 UTC, daradurvs commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxAdapter.java
> +            else if (prev == SUSPENDED)
В else if проверяется не state, не нарушиться ли логика выполнения?
т.е. если state != ACTIVE не надо ли проверять prev?

2017-07-21 12:41 UTC, daradurvs commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxAdapter.java
> +            //No-op.
Пропущен пробел.
// No-op. (для единого стиля во всем PR)

2017-07-21 12:41 UTC, daradurvs commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxAdapter.java
> +            //No-op.
Пропущен пробел.
// No-op. (для единого стиля во всем PR)

2017-07-21 12:41 UTC, daradurvs commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxLocalAdapter.java
> +                threadId = Thread.currentThread().getId();
Правильно ли в методе которые по названию проверяет состояние,
присваивать переменную класса?
Может привести диагностируемым ошибкам.
Если да, то лучше поменять местами с
state(MARKED_ROLLBACK, true);
Чтобы не возникало сомнений не забыты ли фигурные скобки разработчиком.

2017-07-21 12:41 UTC, daradurvs commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxManager.java
> +     * Please don't use directly. Use tx.suspend() instead.
По возможности, надо в методе предусмотреть проверку что она не вызвана напрямую, а не через tx.suspend()
В javadoc "tx.suspend()" обернуть в {@code }

2017-07-21 12:41 UTC, daradurvs commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxManager.java
> +     * Please don't use directly. Use tx.resume() instead.
По возможности, надо в методе предусмотреть проверку что она не вызвана напрямую, а не через tx.suspend()
В javadoc "tx.resume()" обернуть в {@code }

2017-07-21 12:41 UTC, daradurvs commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxMap.java
> +    IgniteTxMap unseal() {
Package access?

2017-07-21 12:41 UTC, daradurvs commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxMap.java
> +     * @return This map for chaining.
* @return {@code this} for chaining.

2017-07-21 12:41 UTC, daradurvs commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/TransactionProxyImpl.java
> +     * Enters a call without check for not {@code SUSPENDED} status
Точка в конце.

2017-07-21 12:41 UTC, daradurvs commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/TransactionProxyImpl.java
> +        assert (threadId() == Thread.currentThread().getId()) ||
Возможно лучше проверку состояния вынести в отдельный assert

2017-07-21 12:41 UTC, daradurvs commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/IgniteOptimisticTxSuspendResumeTest.java
> +
Ненужная новая линия.

2017-07-21 12:41 UTC, daradurvs commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/IgniteOptimisticTxSuspendResumeTest.java
> +        doProhibitedOperationAfter(operationBefore, "1");
Новая линия.

2017-07-21 12:41 UTC, daradurvs commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/IgniteOptimisticTxSuspendResumeTest.java
> +        doProhibitedOperationAfter(operationBefore, null);
Новая линия.

2017-07-21 12:41 UTC, daradurvs commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/IgniteOptimisticTxSuspendResumeTest.java
> +        doProhibitedOperationAfter(operationBefore, null);
Новая линия.

2017-07-21 12:41 UTC, daradurvs commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/IgniteOptimisticTxSuspendResumeTest.java
> +        doProhibitedOperationAfter(operationBefore, null);
Новая линия.

2017-07-21 12:41 UTC, daradurvs commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/IgniteOptimisticTxSuspendResumeTest.java
> +    private void doProhibitedOperationAfter(final CI1<Transaction> operationBefore,
Missed Javadoc.

2017-07-21 12:41 UTC, daradurvs commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/IgniteOptimisticTxSuspendResumeTest.java
> +
Лишние 2 линии.

2017-07-21 12:41 UTC, daradurvs commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/IgniteOptimisticTxSuspendResumeTest.java
> +     * Closure that can throw any exception
Точка в конце.

2017-07-21 12:41 UTC, daradurvs commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/IgniteOptimisticTxSuspendResumeTest.java
> +     * @param <T> type of closure parameter
Точка в конце. "type" с большой буквы

2017-07-21 12:41 UTC, daradurvs commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/IgniteOptimisticTxSuspendResumeTest.java
> +        public abstract void applyx(T o) throws Exception;
Missed javadoc.

2017-07-21 12:41 UTC, daradurvs commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/IgniteOptimisticTxSuspendResumeTest.java
> +        @Override public void apply(T o) {
/** {@inheritDoc} */

2017-07-21 12:41 UTC, daradurvs commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/IgniteOptimisticTxSuspendResumeTest.java
> +        @Override public void run() {
/** {@inheritDoc} */

2017-07-21 12:41 UTC, daradurvs commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/IgniteOptimisticTxSuspendResumeTest.java
> +        abstract void runx() throws Exception;
Модификатор public + Javadoc

2017-07-21 12:41 UTC, daradurvs commented on modules/jta/src/main/java/org/apache/ignite/internal/processors/cache/jta/CacheJtaResource.java
> +        if ((flags & TMRESUME) == TMRESUME)
Фигурные скобки.

2017-07-21 12:41 UTC, daradurvs commented on modules/jta/src/main/java/org/apache/ignite/internal/processors/cache/jta/CacheJtaResource.java
> +        if ((flags & TMSUSPEND) == TMSUSPEND)
Фигурные скобки.
Думаю что стоит опустить условие после if ((flags & TMFAIL) > 0)

2017-07-21 12:41 UTC, daradurvs commented on modules/jta/src/main/java/org/apache/ignite/internal/processors/cache/jta/CacheJtaResource.java
> +    GridNearTxLocal cacheTx() {
Модификатор доступа не нужен?
Пропущен Javadoc.

2017-07-21 12:41 UTC, daradurvs commented on modules/jta/src/test/java/org/apache/ignite/internal/processors/cache/GridJtaTransactionManagerSelfTest.java
> +                opSuc = true;
Необходимо убрать флаг opSuc, заменить на конструкцию fail()

2017-07-21 13:32 UTC, nizhikov commented on modules/jta/src/main/java/org/apache/ignite/internal/processors/cache/jta/CacheJtaResource.java
> +        if ((flags & TMRESUME) == TMRESUME)
done

2017-07-21 13:32 UTC, nizhikov commented on modules/jta/src/main/java/org/apache/ignite/internal/processors/cache/jta/CacheJtaResource.java
> +    GridNearTxLocal cacheTx() {
нет. это package private

2017-07-21 13:32 UTC, nizhikov commented on modules/jta/src/main/java/org/apache/ignite/internal/processors/cache/jta/CacheJtaResource.java
> +    GridNearTxLocal cacheTx() {
добавил коммент

2017-07-21 13:32 UTC, nizhikov commented on modules/jta/src/test/java/org/apache/ignite/internal/processors/cache/GridJtaTransactionManagerSelfTest.java
> +                opSuc = true;
done

2017-07-21 13:32 UTC, nizhikov commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearTxLocal.java
> +    /** Flag to indicate that current thread perform transaction suspension. */
Логика нарушается:

1. установка статуса это `public` метод. Т.е. снаружи любой клиент может установить определённый статус транзакции.

2. в txManager'е `suspendInProgress`, `resumeInProgress` будет `true` только для потока, который вызвал `tx.resume`, `tx.suspend`

2017-07-21 13:32 UTC, nizhikov commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearTxLocal.java
> +    private AffinityTopologyVersion txTopForSuspension;
Кэшируется значение из ThreadLocal переменной в TransactionManager'е.
ThreadLocal сделать нельзя, т.к. это значение передаётся в поток, который делает resume транзакции

2017-07-21 13:32 UTC, nizhikov commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/distributed/near/GridNearTxLocal.java
> +
не забыто. т.к. любой поток кроме, владеющего транзакцией не пройдёт дальше условия

`threadId() != Thread.currentThread().getId()`, поэтому, синхронизация не нужна.
А при resume возможен параллельный вызов метода из разных потоков, поэтому, необходима синхронизация

2017-07-21 13:32 UTC, nizhikov commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxAdapter.java
> +            else if (prev == SUSPENDED)
логика была следующая 
`если состояние *стало* неактивным вызывать seal`.

теперь логика

`если состояние стало *активным* и было SUSPENDED`, то откатить seal с помощью unseal

2017-07-21 13:32 UTC, nizhikov commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxAdapter.java
> +            //No-op.
Скопировал из комментария выше, который без пробела :)

2017-07-21 13:32 UTC, nizhikov commented on modules/jta/src/main/java/org/apache/ignite/internal/processors/cache/jta/CacheJtaResource.java
> +        if ((flags & TMSUSPEND) == TMSUSPEND)
done

2017-07-21 13:32 UTC, nizhikov commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxAdapter.java
> +            //No-op.
done

2017-07-21 13:32 UTC, nizhikov commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxLocalAdapter.java
> +                threadId = Thread.currentThread().getId();
1. Строчкой ниже идёт смена статуса транзакции. Т.е. метод не просто проверяет состояние.
2. При попытке resume транзакции по которой уже наступил таймаут у неё будет threadId == `UNDEFINED_THREAD_ID` и `state(MARKED_ROLLBACK)` в этом месте, что является неверным состоянием.
Вообще, видимо, здесь надо делать `resume` транзакции и тут же её откатывать.

2017-07-21 13:32 UTC, nizhikov commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxManager.java
> +     * Please don't use directly. Use tx.suspend() instead.
Проверка уже есть.

`suspendInProgress==true` только для потока, который вызвал `tx.suspend`

2017-07-21 13:32 UTC, nizhikov commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxManager.java
> +     * Please don't use directly. Use tx.resume() instead.
Проверка уже есть.

`resumeInProgress==true` только для потока, который вызвал `tx.resume`

2017-07-21 13:32 UTC, nizhikov commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxMap.java
> +     * @return This map for chaining.
done

2017-07-21 13:32 UTC, nizhikov commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/IgniteTxMap.java
> +    IgniteTxMap unseal() {
метод сделан по аналогии с `seal`, там модификатор видимости такой же.
Видимо, так и надо.

2017-07-21 13:32 UTC, nizhikov commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/TransactionProxyImpl.java
> +     * Enters a call without check for not {@code SUSPENDED} status
done

2017-07-21 13:32 UTC, nizhikov commented on modules/core/src/main/java/org/apache/ignite/internal/processors/cache/transactions/TransactionProxyImpl.java
> +        assert (threadId() == Thread.currentThread().getId()) ||
Не придумал как.
Проверка такая: текущий поток либо должен владеть транзакцией, либо это транзакция ничья и в статусе `SUSPENDED`

2017-07-21 13:57 UTC, nizhikov commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/IgniteOptimisticTxSuspendResumeTest.java
> +
done

2017-07-21 13:57 UTC, nizhikov commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/IgniteOptimisticTxSuspendResumeTest.java
> +        doProhibitedOperationAfter(operationBefore, "1");
done

2017-07-21 13:57 UTC, nizhikov commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/IgniteOptimisticTxSuspendResumeTest.java
> +        doProhibitedOperationAfter(operationBefore, null);
done

2017-07-21 13:57 UTC, nizhikov commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/IgniteOptimisticTxSuspendResumeTest.java
> +        doProhibitedOperationAfter(operationBefore, null);
done

2017-07-21 13:57 UTC, nizhikov commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/IgniteOptimisticTxSuspendResumeTest.java
> +        doProhibitedOperationAfter(operationBefore, null);
done

2017-07-21 13:57 UTC, nizhikov commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/IgniteOptimisticTxSuspendResumeTest.java
> +    private void doProhibitedOperationAfter(final CI1<Transaction> operationBefore,
done

2017-07-21 13:57 UTC, nizhikov commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/IgniteOptimisticTxSuspendResumeTest.java
> +     * Closure that can throw any exception
done

2017-07-21 13:57 UTC, nizhikov commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/IgniteOptimisticTxSuspendResumeTest.java
> +     * @param <T> type of closure parameter
done

2017-07-21 13:57 UTC, nizhikov commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/IgniteOptimisticTxSuspendResumeTest.java
> +        @Override public void apply(T o) {
done

2017-07-21 13:57 UTC, nizhikov commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/IgniteOptimisticTxSuspendResumeTest.java
> +        public abstract void applyx(T o) throws Exception;
done

2017-07-21 13:57 UTC, nizhikov commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/IgniteOptimisticTxSuspendResumeTest.java
> +        @Override public void run() {
done

2017-07-21 13:57 UTC, nizhikov commented on modules/core/src/test/java/org/apache/ignite/internal/processors/cache/distributed/IgniteOptimisticTxSuspendResumeTest.java
> +        abstract void runx() throws Exception;
done

2017-07-21 14:03 UTC, closed without merging